version: "3.7"
services:
  web:
    build: project
    restart: always
    ports:
      - "8000:8000"

    networks:
      - flask_network


  proxy:
    build: proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - flask_network

  db:
    container_name: postgres_container
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    networks:
      - flask_network
    environment:
      - POSTGRES_DATABASE=fms_v3_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=flask_db4
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  flask_network:
volumes:
  postgres_data:
  pgadmin-data: